# name: RSS Fetcher Cron

# on:
#   schedule:
#     # Run every minute to avoid GitHub cron delays
#     - cron: "*/5 0-17 * * *"
#   workflow_dispatch:

# concurrency:
#   group: rss-fetcher
#   cancel-in-progress: false

# jobs:
#   run-rss:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check allowed minute
#         id: timecheck
#         run: |
#           MINUTE=$(date +'%M')
#           if [[ "$MINUTE" != "15" && "$MINUTE" != "45" ]]; then
#             echo "skip=true" >> $GITHUB_OUTPUT
#             echo "Skipping run at minute $MINUTE"
#           else
#             echo "Running job at minute $MINUTE"
#           fi

#       - name: Checkout repo
#         if: steps.timecheck.outputs.skip != 'true'
#         uses: actions/checkout@v4

#       - name: Setup Python
#         if: steps.timecheck.outputs.skip != 'true'
#         uses: actions/setup-python@v5
#         with:
#           python-version: "3.9"

#       - name: Cache virtual environment
#         if: steps.timecheck.outputs.skip != 'true'
#         uses: actions/cache@v4
#         with:
#           path: .venv
#           key: venv-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

#       - name: Create venv and install dependencies
#         if: steps.timecheck.outputs.skip != 'true'
#         run: |
#           python -m venv .venv
#           source .venv/bin/activate
#           pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run RSS Fetcher
#         if: steps.timecheck.outputs.skip != 'true'
#         env:
#           HUGGINGFACE_API_TOKEN: ${{ secrets.HUGGINGFACE_API_TOKEN }}
#           MONGODB_URI: ${{ secrets.MONGODB_URI }}
#         run: |
#           source .venv/bin/activate
#           python -m cron.main
