name: Build Docker Image

on:
  workflow_dispatch:
  # push:
    # branches: [main]  # Build the image whenever you push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Login to GitHub Container Registry (GHCR).
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Build Docker image
      - name: Build image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/rss-runner:latest .

      # 4️⃣ Push Docker image
      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/rss-runner:latest